#!/usr/bin/env node

const url = require('url')
const { spawn } = require('child_process')
const { homedir } = require('os')
const { parse: parseHtml } = require('node-html-parser')

const { QUTE_URL, QUTE_TITLE, QUTE_MODE, QUTE_SELECTED_HTML } = process.env
const q = url.parse(QUTE_URL, true)

const { v: videoId } = q.query

if (QUTE_MODE === 'hints') {
  const parsedHtml = parseHtml(QUTE_SELECTED_HTML)
  const description = parsedHtml.querySelector('#video-title').textContent.trim()
  capture(`[[yt:${videoId}][${description}]]`)
} else {
  capture(`[[yt:${videoId}][${QUTE_TITLE.replace(/ - YouTube/g, '')}]]`)
}

function capture(string) {
  detachableCommand(`${homedir()}/.emacs.d/bin/org-capture`, ['-k', 'np', string])
}

function detachableCommand(...args) {
  const child = spawn(...args, { detached: true })
  child.unref()
}
