#!/bin/dash

if [ $COMPUTER_IDENTIFIER = "main-desktop" ]; then
  export ULTRA_WIDE_MONITOR="DisplayPort-3"
  xrandr \
    --output DisplayPort-3 --mode 5120x1440 --rate 59.98 --primary --pos 0x2160 \
    --output DisplayPort-2 --auto --pos 640x0

  bspc monitor DisplayPort\-3 -d 1 2 3 4 5 6 7 8
  bspc monitor DisplayPort\-2 -d 9 10
  bspc wm -O DisplayPort\-3 DisplayPort\-2
fi

if [ $COMPUTER_IDENTIFIER = "work-laptop" ]; then
  numberOfMonitorsConnected=$(xrandr -d :0 -q | grep ' connected' | wc -l)

  if [ "$numberOfMonitorsConnected" -gt "2" ]; then

    # export LEFT_MONITOR="eDP1"
    # export CENTER_MONITOR="HDMI-1-3"
    # export RIGHT_MONITOR="DP-1-3"
    # export CENTER_POLYBAR_BOTTOM="true"
    #
    # bspc monitor eDP1 -d 1 2 3
    # bspc monitor HDMI\-1\-3 -d 4 5 6 7
    # bspc monitor DP\-1\-3 -d 8 9 10
    # export LEFT_MONITOR="eDP1"
    # export CENTER_MONITOR="DP1-3"
    # export RIGHT_MONITOR="DP1-1"
    export LEFT_MONITOR="eDP-1-1"
    export CENTER_MONITOR="DP-1-1-3"
    export RIGHT_MONITOR="DP-1-1-1"
    export CENTER_POLYBAR_BOTTOM="true"
    export EMACS_FONT_SIZE="20"

    # bspc monitor eDP1 -d 1 2 3
    # bspc monitor DP1\-3 -d 4 5 6 7
    # bspc monitor DP1\-1 -d 8 9 10
    bspc monitor DP\-1\-1\-1 -d 7 8 9 10
    bspc monitor DP\-1\-1\-3 -d 2 3 4 5 6
    bspc monitor eDP\-1\-1 -d 1

    polybar middle-$COMPUTER_IDENTIFIER &
    polybar left &
    polybar right &
  elif [ "$numberOfMonitorsConnected" -gt "1" ]; then
    export RIGHT_MONITOR="eDP-1-1"
    export CENTER_MONITOR="DP-1-1"
    export CENTER_POLYBAR_BOTTOM="true"
    export ULTRA_WIDE_MONITOR=$CENTER_MONITOR

    bspc monitor DP\-1\-1 -d 1 2 3 4 5 6 7 8
    bspc monitor eDP\-1\-1 -d 9 10

    polybar middle-$COMPUTER_IDENTIFIER &
    polybar right &
  else
    # This should include more. Maybe in sync with udev?
    export CENTER_MONITOR="eDP-1-1"
    bspc monitor -d 1 2 3 4 5 6 7 8 9 10
    polybar middle-$COMPUTER_IDENTIFIER-hidpi &
    export EMACS_FONT_SIZE="28"
  fi
fi

# bspc config border_width 15
bspc config window_gap 0

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle true
bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true
bspc config pointer_follows_focus true

bspc config external_rules_command ~/.config/bspwm/external_rules
bspc rule -a mpv state=floating border=off
bspc rule -a MPlayer state=floating border=off
bspc rule -a qutebrowser border=off
bspc rule -a Blueman-manager state=floating
bspc rule -a Alacritty border=off
bspc rule -a "org.wezfurlong.wezterm" border=off
bspc rule -a st border=off
bspc rule -a jetbrains-idea border=off
bspc rule -a Surf state=tiled
bspc rule -a Emacs state=tiled border=off
# bspc rule -a "doom-capture" state=floating
bspc rule -a "Microsoft Teams - Insiders" state=floating

# autostart
setxkbmap -option compose:ralt
clipit &
pasystray &
nextcloud --background &
emacs --daemon -n &
flameshot &
# $HOME/.config/bspwm/layout.sh &
picom --experimental-backends -b

if [ $COMPUTER_IDENTIFIER = "main-desktop" ]; then
  $HOME/.config/polybar/launch.sh
  indicator-kdeconnect &
fi

if [ $COMPUTER_IDENTIFIER = "work-laptop" ]; then
  # conky -c ~/.config/conky/conky.conf &
  nm-applet &
  # systemctl --user start mopidy
fi

feh --bg-fill $WALLPAPER
