#! /bin/sh

if [ $COMPUTER_IDENTIFIER = "main-desktop" ]; then
  xrandr --output HDMI2 --auto --output DP1 --primary --auto --right-of HDMI2 --output DP2 --auto --right-of DP1
  bspc monitor $LEFT_MONITOR -d 1 2 3
  bspc monitor $CENTER_MONITOR -d 4 5 6 7
  bspc monitor $RIGHT_MONITOR -d 8 9 10
fi

if [ $COMPUTER_IDENTIFIER = "work-laptop" ]; then
  # This should include more. Maybe in sync with udev?
  bspc monitor -d 1 2 3 4 5 6 7 8 9 10
fi

bspc config border_width 1
bspc config window_gap 12

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true

bspc config external_rules_command ~/.config/bspwm/external_rules
bspc rule -a mpv state=floating border=off
bspc rule -a Blueman-manager state=floating

# autostart
setxkbmap -option compose:ralt
compton -b
xscreensaver &
clipit &
pasystray &
blueman-applet &

if [ $COMPUTER_IDENTIFIER = "main-desktop" ]; then
  redshift -l $LAT_LON &
  dropbox &
  $HOME/.config/polybar/launch.sh
fi

if [ $COMPUTER_IDENTIFIER = "work-laptop" ]; then
  polybar middle &
  conky -c ~/.config/conky/conky.conf &
  nm-applet &
  # hamster &
fi

feh --bg-fill $WALLPAPER
