#!/bin/dash

if [ $COMPUTER_IDENTIFIER = "main-desktop" ]; then
  xrandr --output HDMI2 --auto --output DP2 --primary --auto --right-of HDMI2 --output DP1 --auto --right-of DP2
  bspc monitor $LEFT_MONITOR -d 1 2 3
  bspc monitor $CENTER_MONITOR -d 4 5 6 7
  bspc monitor $RIGHT_MONITOR -d 8 9 10
fi

if [ $COMPUTER_IDENTIFIER = "work-laptop" ]; then
  numberOfMonitorsConnected=$(xrandr -d :0 -q | grep ' connected' | wc -l)

  if [ "$numberOfMonitorsConnected" -gt "2" ]; then

    export LEFT_MONITOR="eDP1"
    export CENTER_MONITOR="DP1-1"
    export RIGHT_MONITOR="DP1-2"
    export CENTER_POLYBAR_BOTTOM="true"

    bspc monitor eDP1 -d 1 2 3
    bspc monitor DP1\-1 -d 4 5 6 7
    bspc monitor DP1\-2 -d 8 9 10

    polybar middle-$COMPUTER_IDENTIFIER &
    polybar left &
    polybar right &
  else
    # This should include more. Maybe in sync with udev?
    bspc monitor -d 1 2 3 4 5 6 7 8 9 10
    polybar middle-$COMPUTER_IDENTIFIER &
  fi
fi

bspc config border_width 15
bspc config window_gap 30

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true
bspc config normal_border_color \#2e3440
bspc config active_border_color \#2e3440
bspc config focused_border_color \#2e3440

bspc config external_rules_command ~/.config/bspwm/external_rules
bspc rule -a mpv state=floating border=off
bspc rule -a Blueman-manager state=floating
bspc rule -a jetbrains-idea border=off
bspc rule -a Surf state=tiled

# autostart
setxkbmap -option compose:ralt
setxkbmap -option caps:escape
compton -b --config="$HOME/.config/compton/compton.conf"
xscreensaver &
clipit &
pasystray &
blueman-applet &
redshift-gtk -l $LAT_LON &

if [ $COMPUTER_IDENTIFIER = "main-desktop" ]; then
  dropbox &
  $HOME/.config/polybar/launch.sh
fi

if [ $COMPUTER_IDENTIFIER = "work-laptop" ]; then
  conky -c ~/.config/conky/conky.conf &
  nm-applet &
  systemctl --user start mopidy
  # hamster &
fi

feh --bg-fill $WALLPAPER
