#! /bin/sh

wid=$1
class=$2
instance=$3

if [ "$instance" = "pass-popup" ]; then
  echo "state=floating"
  echo "focus=on"
  echo "border=off"
  
  xdotool windowsize $wid 50% 40% windowmove $wid 25% 7% windowactivate $wid
  exit 0
fi

if [ "$instance" = "ncmpcpp-popup" ]; then
  echo "state=floating"
  echo "focus=on"
  echo "border=off"
  
  xdotool windowsize $wid 80% 80% windowmove $wid 10% 10% windowactivate $wid
  exit 0
fi

if [ "$instance" = "ranger-popup" ]; then
  echo "state=floating"
  echo "focus=on"
  echo "border=off"
  
  xdotool windowsize $wid 80% 80% windowmove $wid 10% 10% windowactivate $wid
  exit 0
fi
