#!/usr/bin/env bash

FONT='Knanck 10'

background="25374A"
foreground="3A526B"
b_background="131D24"

rofi_command="rofi -dmenu -show run -font '${FONT}' -fg '#${foreground}' -bg '#${background}' -hlfg '#${foreground}' -hlbg '#${background}' -bc '#${b_background}' -location 0 -lines 8 -bw 0 -fuzzy -fullscreen -padding 400 -separator-style none"

i3-dmenu-desktop --dmenu="${rofi_command}"
