#!/bin/sh

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
eval "$(gnome-keyring-daemon --start)"
export SSH_AUTH_SOCK

# for screen sharing: https://wiki.archlinux.org/title/PipeWire#WebRTC_screen_sharing

if [ "$COMPUTER_IDENTIFIER" = "main-desktop" ]; then
  riverctl spawn "gsettings set org.gnome.desktop.interface gtk-theme 'Vimix-Dark-Doder'"
  riverctl spawn "gsettings set org.gnome.desktop.interface icon-theme 'Papirus-Dark'"
  riverctl spawn "wlr-randr --output DP-4 --on --custom-mode 5120x1440@60Hz"
  riverctl spawn "kanshi -c /home/stianlj/.config/kanshi/config-main-desktop"
  riverctl spawn "waybar -c /home/stianlj/.config/waybar/config-main-desktop"
elif [ "$COMPUTER_IDENTIFIER" = "work-laptop" ]; then
  riverctl spawn "gsettings set org.gnome.desktop.interface gtk-theme 'Catppuccin-pink'"
  riverctl spawn "gsettings set org.gnome.desktop.interface cursor-theme 'Catppuccin Blue'"
  riverctl spawn "gsettings set org.gnome.desktop.interface icon-theme 'Papirus'"
  riverctl xcursor-theme 'Catppuccin Blue'
  riverctl spawn "kanshi -c /home/stianlj/.config/kanshi/config"
  riverctl spawn "waybar -c /home/stianlj/.config/waybar/config-work-laptop"
fi
riverctl spawn "swaybg -m fit -i $WALLPAPER"
riverctl spawn "rivercarro -no-smart-gaps -main-ratio 0.5"

riverctl default-layout rivercarro

riverctl map normal Super w close

riverctl map normal Super Return spawn "kitty fish"
riverctl map normal Super d spawn "wofi --show drun --allow-images --no-actions"
riverctl map normal Super Backspace spawn "wlogout --buttons-per-row 2 --column-spacing 20 --row-spacing 20 -p layer-shell"

riverctl map normal Control+Alt H spawn "clipman pick -t wofi"

riverctl map normal Super+Shift E exit

riverctl map normal Super L focus-view next
riverctl map normal Super H focus-view previous

# Super+Shift+J and Super+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal Super+Shift L swap next
riverctl map normal Super+Shift H swap previous

# Super+Period and Super+Comma to focus the next/previous output
riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous

# Super+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous

# Super+H and Super+L to decrease/increase the main ratio of rivercarro(1)
riverctl map normal Super J send-layout-cmd rivercarro "main-ratio -0.05"
riverctl map normal Super K send-layout-cmd rivercarro "main-ratio +0.05"

# Super+Shift+H and Super+Shift+L to increment/decrement the main count of rivercarro(1)
riverctl map normal Super+Shift J send-layout-cmd rivercarro "main-count +1"
riverctl map normal Super+Shift K send-layout-cmd rivercarro "main-count -1"

# Super+Alt+{H,J,K,L} to move views
riverctl map normal Super+Alt H move left 100
riverctl map normal Super+Alt J move down 100
riverctl map normal Super+Alt K move up 100
riverctl map normal Super+Alt L move right 100

# Super+Alt+Control+{H,J,K,L} to snap views to screen edges
riverctl map normal Super+Alt+Control H snap left
riverctl map normal Super+Alt+Control J snap down
riverctl map normal Super+Alt+Control K snap up
riverctl map normal Super+Alt+Control L snap right

# Super+Alt+Shif+{H,J,K,L} to resize views
riverctl map normal Super+Alt+Shift H resize horizontal -100
riverctl map normal Super+Alt+Shift J resize vertical 100
riverctl map normal Super+Alt+Shift K resize vertical -100
riverctl map normal Super+Alt+Shift L resize horizontal 100

# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view

# Super + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

for i in {1..5}; do
  tags=$((1 << ($i - 1)))
  riverctl map normal Super $i set-focused-tags $tags
  riverctl map normal Super+Shift $i set-view-tags $tags
  riverctl map normal Super+Control $i toggle-focused-tags $tags
  riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 5) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

# Super+Space to toggle float
riverctl map normal Super S toggle-float

# Super+F to toggle fullscreen
riverctl map normal Super F toggle-fullscreen

# Super+{Up,Right,Down,Left} to change layout orientation
riverctl map normal Super Up send-layout-cmd rivercarro "main-location top"
riverctl map normal Super Right send-layout-cmd rivercarro "main-location right"
riverctl map normal Super Down send-layout-cmd rivercarro "main-location bottom"
riverctl map normal Super Left send-layout-cmd rivercarro "main-location left"

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked; do
  # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
  riverctl map $mode None XF86AudioRaiseVolume spawn 'pamixer -i 5'
  riverctl map $mode None XF86AudioLowerVolume spawn 'pamixer -d 5'
  riverctl map $mode None XF86AudioMute spawn 'pamixer --toggle-mute'

  # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
  riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
  riverctl map $mode None XF86AudioPlay spawn 'playerctl play-pause'
  riverctl map $mode None XF86AudioPrev spawn 'playerctl previous'
  riverctl map $mode None XF86AudioNext spawn 'playerctl next'

  # Control screen backlight brighness with light (https://github.com/haikarainen/light)
  riverctl map $mode None XF86MonBrightnessUp spawn 'light -A 5'
  riverctl map $mode None XF86MonBrightnessDown spawn 'light -U 5'
done

riverctl border-width 0

# Set keyboard repeat rate
riverctl set-repeat 50 300

riverctl focus-follows-cursor normal
riverctl set-cursor-warp on-output-change

# Make certain views start floating
riverctl float-filter-add app-id float
riverctl float-filter-add app-id mpv
riverctl float-filter-add title "popup title with spaces"

riverctl spawn "wl-paste -pw wl-copy"
riverctl spawn "wl-paste -p -t text --watch clipman store -P --histpath=\"~/.local/share/clipman-primary.json\""
riverctl spawn "sleep 1; nextcloud --logfile /tmp/nextcloud.log --background"
# riverctl spawn "swhks &"
# riverctl spawn "pkexec swhkd"

if [ "$COMPUTER_IDENTIFIER" = "work-laptop" ]; then
  riverctl spawn "sleep 1; /usr/bin/nm-applet --indicator"
fi
